# Generated by Django 5.2.1 on 2025-06-02 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='tmdb_id',
            new_name='md_id',
        ),
    ]
